Fix error handling in virSecurityManagerGetMountOptions
The impls of virSecurityManagerGetMountOptions had no way to
return errors, since the code was treating 'NULL' as a success
value. This is somewhat pointless, since the calling code did
not want NULL in the first place and has to translate it into
the empty string "". So change the code so that the impls can
return "" directly, allowing use of NULL for error reporting
once again

Signed-off-by: Daniel P. Berrange <berrange@redhat.com>
(cherry picked from commit 3f6470f7532eecdca5687a2dbbc5e25610d8030b)

Conflicts:

	src/lxc/lxc_container.c - just git being overly cautious

Fixes:
Error: CHECKED_RETURN (CWE-252):
libvirt-0.10.2/src/security/security_selinux.c:1981:
    unchecked_value: No check of the return value of "virAsprintf(&opts,
    ",context=\"%s\"", (char const *)secdef->imagelabel)".
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=878376