Add virtio-scsi to fallback models of scsi controller
https://bugzilla.redhat.com/show_bug.cgi?id=1040141

When user does not specify any model for scsi controller, or worse, no
controller at all, but libvirt automatically adds scsi controller with
no model, we are not searching for virtio-scsi and thus this can fail
for example on qemu which doesn't support lsi logic adapter.

This means that when qemu on x86 doesn't support lsi53c895a and the
user adds the following to an XML without any scsi controller:

<disk ...>
  ...
  <target dev='sda'>
</disk>

libvirt fails like this:
 # virsh define asdf.xml
 error: Failed to define domain from asdf.xml
 error: internal error Unable to determine model for scsi controller

Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=974943
(cherry picked from commit b7f1c0c38729e5eba44ba134b93b1b95a4dae8d8)

adjusted for differences in 6.5 code base

The 6.6 patch is the same and was posted as:

http://post-office.corp.redhat.com/archives/rhvirt-patches/2013-December/msg00076.html

Signed-off-by: John Ferlan <jferlan@redhat.com>
Signed-off-by: Jiri Denemark <jdenemar@redhat.com>