build: Fix build with -Werror
https://bugzilla.redhat.com/show_bug.cgi?id=976401

Commit 752596b5 broke the build with -Werror

qemu/qemu_hotplug.c: In function 'qemuDomainChangeGraphics':
qemu/qemu_hotplug.c:1980:39: error: declaration of 'listen' shadows a
  global declaration [-Werror=shadow]

Fix with s/listen/newlisten/
(cherry picked from commit 24d0e67aba6b9d62cfee95582f211b4d850373d3)