util: escapes special characters in VIR_LOG_REGEX
https://bugzilla.redhat.com/show_bug.cgi?id=954248

In debug mode, the bug failed to start vm
error: Failed to start domain rhel5u9
error: internal error Out of space while reading console log output:
...
(cherry picked from commit eb086eb5b58c771cb3f731ef2169dab6a8967cff)