virsh: distinguish errors between missing argument and wrong option
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=924596
(cherry picked from commit dd71fa110a05ae480a445a75e7c454914f42789c)
Specifying ':' to suppress the error messages printed by getopt().
Then, distinguish the two types of errors.

Before:
 # virsh -c
   virsh: option requires an argument -- 'c'
   error: unsupported option '-?'. See --help.

After:
 # virsh -c
   error: option '-c' requires an argument

 # virsh -x
   error: unsupported option '-x'. See --help.