qemuDomainGetVcpusFlags: Initialize ncpuinfo
https://bugzilla.redhat.com/show_bug.cgi?id=924400

Currently, there's a path to use the ncpuinfo variable uninitialized,
which leads to a compiler warning:

    qemu/qemu_driver.c: In function 'qemuDomainGetVcpusFlags':
    qemu/qemu_driver.c:4573:9: error: 'ncpuinfo' may be used
    uninitialized in this function [-Werror=maybe-uninitialized]
             for (i = 0; i < ncpuinfo; i++) {
             ^
(cherry picked from commit cdd823c073c30f9f3e4f10d38dbe73694ca538ac)