qemu: Stop recursive detection of image chains when an image is missing
https://bugzilla.redhat.com/show_bug.cgi?id=878862

Commit e0c469e58b93f852a72265919703cb6abd3779f8 that fixes the detection
of image chain wasn't complete. Iteration through the backing image
chain has to stop at the last existing image if some of the images are
missing otherwise the backing chain that is cached contains entries with
paths being set to NULL resulting to:

error: Unable to allow access for disk path (null): Bad address

Fortunately stat() is kind enough not to crash when it's presented with
a NULL argument. At least on Linux.
(cherry picked from commit 58a54dc37340113f83da587387a297d05d5342cf)